import { createHash } from "node:crypto";

import { memory } from "../../ai/config";
import type { MemoryScopeKind } from "../../ai/types";

/*
 * Who a memory is about.
 *
 * This file is small and it is the whole ownership model, so it
 * is worth reading before anything else in this directory.
 *
 * BuildGentic's memory is `User -> Agent -> Memories`, never
 * `User -> Memories`. A learner's Math Tutor remembers that
 * they keep losing marks on related rates; their College Essay
 * Coach knows nothing about it and must not, because an agent
 * that inherits everything its owner ever said to a different
 * agent is not a smarter agent — it is a privacy failure that
 * also gives worse answers, since half of what it "knows" is
 * about something else entirely.
 *
 * So every read and every write below is keyed by an agent AND
 * a subject, and the subject is whoever the agent was actually
 * talking to:
 *
 *   owner      — the learner, testing in the Builder. Their own
 *                memory with this one agent.
 *   deployment — somebody calling the deployed endpoint. A
 *                separate store, namespaced by the deployment,
 *                and optionally split further by a `memoryKey`
 *                the caller supplies for their own end users.
 *
 * The two never mix, and that is deliberate rather than
 * incidental. An anonymous caller must not be able to read what
 * the owner told the agent privately while building it, and the
 * owner must not find a stranger's statements about themselves
 * in their own Test panel. It is the same boundary File
 * Analysis draws between an owner's attachments and a
 * deployment's, drawn the same way: from a verified row, never
 * from a request body.
 *
 * A scope is a RESOLUTION, not a claim. Nothing in this file is
 * ever built from something a caller sent, with one exception —
 * the raw `memoryKey` on the deployed path, which is namespaced
 * under a deployment id that the caller did not choose and
 * cannot reach past. The worst a forged key achieves is a
 * different drawer inside the caller's own deployment.
 */

export type MemoryScope =
  | {
      kind: "owner";
      /* The learner. Also the row's `user_id`, and the person
         whose quota and provider key pay for the work. */
      userId: string;
      agentId: string;
    }
  | {
      kind: "deployment";
      deploymentId: string;
      agentId: string;
      /* The owner, inherited from the deployment row. Still the
         row's `user_id`: an anonymous caller has no account to
         bill, so a deployed agent's remembering spends its
         owner's allowance exactly as its answering does. */
      ownerId: string;
      /* Already hashed. See `subjectFor`. */
      subject: string;
    };

/*
 * The owner of the rows this scope reads and writes.
 *
 * Always a real learner, whichever side is talking. Used as the
 * `user_id` predicate on every query in MemoryStore, which —
 * because the service-role client bypasses RLS — is one of the
 * two things standing between one learner and another's.
 */
export function ownerOf(scope: MemoryScope): string {
  return scope.kind === "owner" ? scope.userId : scope.ownerId;
}

/*
 * The namespace string, matching the generated `scope_key`
 * column in migration 0010.
 *
 * MUST STAY IDENTICAL TO THE SQL. The column is generated by
 * the database and this function is what every query filters
 * on, so a disagreement between them does not produce an error
 * — it produces an agent that writes memories it can never read
 * back, which looks exactly like memory not working. The verify
 * suite compares the two by round-tripping a written row.
 *
 * The owner half is namespaced by the owner's user id rather
 * than by a constant like "owner", which matters more than it
 * looks: a constant would give every learner on the platform
 * the same scope key, and a search function filtering on scope
 * alone would then be a cross-tenant read. It filters on the
 * agent and the user as well, so that would not actually leak —
 * but a key that is only safe because of the predicates around
 * it is a key waiting for somebody to drop a predicate.
 */
export function scopeKeyOf(scope: MemoryScope): string {
  return scope.kind === "owner"
    ? `${scope.userId}:`
    : `${scope.deploymentId}:${scope.subject}`;
}

export function scopeKindOf(scope: MemoryScope): MemoryScopeKind {
  return scope.kind;
}

/*
 * Turns a caller's `memoryKey` into something safe to store.
 *
 * Hashed, and salted with the deployment id, for a reason that
 * is about the owner's integration rather than about attacks: an
 * owner wiring this endpoint into their own product will reach
 * for the identifier they already have, which is an email
 * address or a user id from their database. Storing that raw
 * would make BuildGentic hold a list of their customers as a side
 * effect of a memory feature nobody asked to be a directory.
 *
 * A digest isolates exactly as well — the same key always lands
 * in the same drawer — and leaves the owner's Memory screen
 * saying "three people" instead of naming them.
 *
 * The deployment id is the salt so the same email under two
 * different deployments produces two different subjects. Without
 * it, an owner with two agents could correlate their callers
 * across both by comparing digests.
 *
 * Returns "" for a caller that sent no key, which is the
 * deployment's own shared drawer. That is the right default: a
 * deployed agent with Memory on and no key still remembers
 * across conversations, which is what the capability promises,
 * and a caller who needs per-person isolation opts into it.
 */
export function subjectFor(
  deploymentId: string,
  memoryKey: string | undefined
): string {
  const raw = (memoryKey ?? "").trim();

  if (!raw) {
    return "";
  }

  return createHash("sha256")
    .update(`${deploymentId}:${raw.slice(0, memory.subjectMaxChars)}`)
    .digest("hex")
    .slice(0, 32);
}

/*
 * A short, stable label for one subject, for the owner's eyes.
 *
 * The digest is 32 characters of hex and nobody can hold that in
 * their head long enough to tell two callers apart on a screen.
 * Eight is plenty to distinguish the handful of end users one
 * learner's deployed agent will have, and it is a prefix of
 * something already irreversible.
 */
export function subjectLabel(subject: string): string {
  return subject ? subject.slice(0, 8) : "shared";
}
