/*
 * Just enough XML to read an Office part.
 *
 * Not a parser, and the distinction matters. OOXML parts are
 * machine-generated by Word and Excel: no DTDs, no entity
 * declarations, no processing instructions worth honouring, no
 * mixed-content ambiguity. What is needed is the ability to walk
 * elements in document order and read their text, and that is a
 * scanner rather than a tree builder.
 *
 * Refusing to build a tree is also the security posture. A real
 * XML parser is where XXE lives — external entities that read
 * files off the server or open connections to reach them — and
 * an OOXML part arrives from a stranger. Nothing here resolves
 * an entity it was not told about, follows a reference, or
 * fetches anything, because there is no code to do so.
 *
 * The five predefined entities are decoded and nothing else is.
 * A `&foo;` that Word did not write stays as written, which is
 * both the honest rendering of an unknown reference and the
 * behaviour that cannot be talked into expanding.
 */

const ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
};

export function decodeXmlText(raw: string): string {
  return raw.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (match, body: string) => {
    if (body[0] === "#") {
      const code =
        body[1] === "x" || body[1] === "X"
          ? Number.parseInt(body.slice(2), 16)
          : Number.parseInt(body.slice(1), 10);

      /* Control characters are left as written rather than
         decoded: a numeric reference to one is either a mistake
         or an attempt to smuggle it past a filter. */
      if (!Number.isFinite(code) || code < 32 || code > 0x10ffff) {
        return match;
      }

      try {
        return String.fromCodePoint(code);
      } catch {
        return match;
      }
    }

    return ENTITIES[body.toLowerCase()] ?? match;
  });
}

export interface XmlTag {
  /* Element name without its namespace prefix, lowercased. */
  name: string;
  /* Raw attribute text, for the few places one is needed. */
  attributes: string;
  closing: boolean;
  /* True for `<br/>`-style elements, which open and close at
     once and therefore have no content. */
  selfClosing: boolean;
}

export type XmlToken =
  | { type: "tag"; tag: XmlTag }
  | { type: "text"; text: string };

/*
 * Walks a part in document order.
 *
 * A generator rather than an array because a sheet can hold tens
 * of thousands of cells and the callers below stop as soon as
 * they have their row limit — materialising the whole token list
 * first would do all the work anyway.
 *
 * CDATA sections and comments are skipped as units. Word does
 * not emit either, but a hand-edited part can, and a scanner
 * that treated `<!-- <w:p> -->` as a paragraph would be reading
 * text nobody wrote.
 */
export function* scanXml(source: string): Generator<XmlToken> {
  let index = 0;

  while (index < source.length) {
    const open = source.indexOf("<", index);

    if (open === -1) {
      const text = source.slice(index);

      if (text) {
        yield { type: "text", text: decodeXmlText(text) };
      }

      return;
    }

    if (open > index) {
      yield { type: "text", text: decodeXmlText(source.slice(index, open)) };
    }

    if (source.startsWith("<!--", open)) {
      const end = source.indexOf("-->", open + 4);
      index = end === -1 ? source.length : end + 3;
      continue;
    }

    if (source.startsWith("<![CDATA[", open)) {
      const end = source.indexOf("]]>", open + 9);
      const text = source.slice(open + 9, end === -1 ? source.length : end);

      if (text) {
        /* Not entity-decoded: CDATA is literal by definition. */
        yield { type: "text", text };
      }

      index = end === -1 ? source.length : end + 3;
      continue;
    }

    if (source.startsWith("<?", open) || source.startsWith("<!", open)) {
      const end = source.indexOf(">", open);
      index = end === -1 ? source.length : end + 1;
      continue;
    }

    const close = source.indexOf(">", open);

    if (close === -1) {
      return;
    }

    const inner = source.slice(open + 1, close);
    const closing = inner.startsWith("/");
    const selfClosing = inner.endsWith("/");

    const body = inner.slice(closing ? 1 : 0, selfClosing ? -1 : undefined);
    const space = body.search(/\s/);

    const qualified = space === -1 ? body : body.slice(0, space);
    const colon = qualified.indexOf(":");

    yield {
      type: "tag",
      tag: {
        name: (colon === -1
          ? qualified
          : qualified.slice(colon + 1)
        ).toLowerCase(),
        attributes: space === -1 ? "" : body.slice(space + 1),
        closing,
        selfClosing,
      },
    };

    index = close + 1;
  }
}

/* One attribute off a tag's raw attribute text. */
export function attribute(attributes: string, name: string): string | null {
  const match = new RegExp(`(?:^|\\s)${name}\\s*=\\s*"([^"]*)"`, "i").exec(
    attributes
  );

  return match ? decodeXmlText(match[1]) : null;
}
