import type { ReactNode } from "react";

import BrandMark from "../../../components/BrandMark";
import type { FlagshipIdentity } from "./identity";

/*
 * The pieces every signature page has to have, and may not
 * reinvent.
 *
 * Five pages designed to feel like five products still have to
 * be five BuildGentic products, and this file is most of what
 * makes that true: the same mark, the same disclosure, the same
 * sentence about what a visitor is talking to. A layout styles
 * these; none of them may leave one out or reword it.
 */

/* =========================================================
   THE MARK

   Present on every page, and a link, because a visitor who
   arrived from a shared URL has no other way to find out what
   BuildGentic is.
========================================================= */

export function BuildGenticMark({ label = "BuildGentic" }: { label?: string }) {
  return (
    <a
      className="fs-mark"
      href="/"
      /* Opens BuildGentic rather than navigating away from a page
         that is not part of it — the same choice the generic
         footer badge makes. */
      target="_blank"
      rel="noreferrer noopener"
    >
      <BrandMark size={14} />
      <span>{label}</span>
    </a>
  );
}

/* =========================================================
   THE FOOTER

   The AI disclosure is NOT optional here.

   A student may turn the "Built with BuildGentic" badge off on
   their own page, and the generic footer then says the plainer
   sentence instead — the point being that a chat box on an
   unfamiliar domain, answering in the first person, is
   something a visitor is entitled to understand. On a flagship
   page nobody can turn anything off, so both halves are always
   drawn: what this is, and who made it.
========================================================= */

export function FlagshipFooter({
  identity,
  children,
}: {
  identity: FlagshipIdentity;
  /* A layout may add its own line — a colophon, a set of rules
     — and it sits above the disclosure, never in place of it. */
  children?: ReactNode;
}) {
  return (
    <footer className="fs-footer">
      {children ? <div className="fs-footer__extra">{children}</div> : null}

      <div className="fs-footer__base">
        <p className="fs-footer__note">{identity.footnote}</p>

        <p className="fs-footer__disclosure">
          Answers are generated by AI and can be wrong.
        </p>

        <BuildGenticMark />
      </div>
    </footer>
  );
}

/* =========================================================
   CAPABILITY LINE

   What the agent can actually do, in a form a layout can drop
   anywhere.

   The facts come from the catalogue — see `flagshipCan` — so
   this cannot promise a capability the agent has had switched
   off. What varies per page is only the wording, which is why
   the caller passes the strings.
========================================================= */

export function CapabilityList({
  items,
  className = "fs-caps",
}: {
  items: Array<{ id: string; label: string; body?: string }>;
  className?: string;
}) {
  if (items.length === 0) {
    return null;
  }

  return (
    <ul className={className}>
      {items.map((item) => (
        <li className={`${className}__item`} key={item.id}>
          <span className={`${className}__label`}>{item.label}</span>
          {item.body ? (
            <span className={`${className}__body`}>{item.body}</span>
          ) : null}
        </li>
      ))}
    </ul>
  );
}
